#!/usr/bin/env sh

# Exit immediately on error and treat unset variables as an error.
set -eu

# Run tests before commit
bun x jest

# Run lint before commit
bun run lint

# Run build before commit
bun run build
